#!/usr/bin/env python3

"""
 @file
 @brief This file is used to launch OpenShot
 @author Jonathan Thomas <jonathan@openshot.org>
 @author Noah Figg <eggmunkee@hotmail.com>

 @mainpage OpenShot Video Editor 2.0

Welcome to the OpenShot Video Editor 2.0 Qt documentation. OpenShot was developed to
 make high-quality video editing and animation solutions freely available to the world. With a focus
 on stability, performance, and ease-of-use, we believe OpenShot is the best cross-platform,
 open-source video editing application in the world!

 This documentation is auto-generated by Doxygen, using the doxypy Python filter. If you are
 interested in how OpenShot Video Editor is designed, feel free to dive in, because this
 documentation was built just for you. If you are not a developer, please feel free to visit
 our main website (http://www.openshot.org/download/), and download a copy today for Linux, Mac, or Windows.

 @section LICENSE

 Copyright (c) 2008-2018 OpenShot Studios, LLC
 (http://www.openshotstudios.com). This file is part of
 OpenShot Video Editor (http://www.openshot.org), an open-source project
 dedicated to delivering high quality video editing and animation solutions
 to the world.

 OpenShot Video Editor is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 OpenShot Video Editor is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with OpenShot Library.  If not, see <http://www.gnu.org/licenses/>.
 """

import sys
import os
import argparse
import atexit
import faulthandler
import json
import logging
import traceback


def _is_packaged_windows_process():
    """Return True when Windows started this process with package identity."""
    if os.name != "nt":
        return False
    try:
        import ctypes
        package_name_length = ctypes.c_uint32()
        result = ctypes.windll.kernel32.GetCurrentPackageFullName(
            ctypes.byref(package_name_length), None)
        return result == 122  # ERROR_INSUFFICIENT_BUFFER means a package name is available.
    except (AttributeError, OSError):
        return False


_msix_diagnostics = (
    os.environ.get("OPENSHOT_MSIX_DIAGNOSTICS") == "1" or
    _is_packaged_windows_process()
)
_msix_log = None
if _msix_diagnostics:
    try:
        _msix_log_dir = os.path.join(
            os.environ.get("LOCALAPPDATA", os.path.expanduser("~")),
            "OpenShot Video Editor")
        os.makedirs(_msix_log_dir, exist_ok=True)
        _msix_log = open(
            os.path.join(_msix_log_dir, "msix-startup.log"),
            "a", encoding="utf-8", buffering=1)
    except OSError:
        _msix_log = None


def _msix_diagnostic(message):
    if _msix_diagnostics:
        line = "[OpenShot MSIX Python] {}".format(message)
        try:
            print(line, file=sys.stderr, flush=True)
        except (AttributeError, OSError):
            pass
        if _msix_log:
            try:
                print(line, file=_msix_log, flush=True)
            except OSError:
                pass


if _msix_diagnostics:
    faulthandler.enable(file=_msix_log or sys.stderr, all_threads=True)
    _msix_diagnostic("Python entry point reached")
    _msix_diagnostic("version={!r}".format(sys.version))
    _msix_diagnostic("executable={!r}".format(sys.executable))
    _msix_diagnostic("argv={!r}".format(sys.argv))
    _msix_diagnostic("cwd={!r}".format(os.getcwd()))
    _msix_diagnostic("__file__={!r}".format(__file__))
    for _variable in (
            "LOCALAPPDATA", "APPDATA", "USERPROFILE", "PATH", "QT_PLUGIN_PATH",
            "QT_QPA_PLATFORM_PLUGIN_PATH", "PYTHONHOME", "PYTHONPATH"):
        _msix_diagnostic("env {}={!r}".format(_variable, os.environ.get(_variable)))

    def _diagnostic_exception(exception_type, exception, exception_traceback):
        _msix_diagnostic("unhandled exception follows")
        traceback.print_exception(
            exception_type, exception, exception_traceback, file=sys.stderr)
        sys.stderr.flush()

    def _diagnostic_audit(event, arguments):
        if event == "import" and arguments:
            _msix_diagnostic("import {!r}".format(arguments[0]))

    sys.excepthook = _diagnostic_exception
    sys.addaudithook(_diagnostic_audit)
    if _msix_log:
        atexit.register(_msix_log.close)
    atexit.register(lambda: _msix_diagnostic("Python process exiting normally"))

# Ensure Qt plugin DLL dependencies are found on Windows packaged builds.
if os.name == "nt":
    _exe_dir = os.path.dirname(os.path.abspath(sys.executable))
    _qt_dll_dirs = [
        os.path.join(_exe_dir, "lib", binding_name)
        for binding_name in ("PyQt{}".format(6), "PySide{}".format(6), "PyQt{}".format(5))
    ]
    _existing_qt_dll_dirs = [path for path in _qt_dll_dirs if os.path.isdir(path)]
    if _existing_qt_dll_dirs:
        os.environ["PATH"] = os.pathsep.join(_existing_qt_dll_dirs + [os.environ.get("PATH", "")])

try:
    # This needs to be imported before the Qt binding
    # To prevent some issues on AppImage build: wrapping/forcing older glibc versions
    _msix_diagnostic("importing openshot")
    import openshot
except ImportError as exc:
    _msix_diagnostic("openshot import failed: {!r}".format(exc))
else:
    _msix_diagnostic("openshot import completed")

# Load user-configured UI scale before importing the Qt binding
scale = 1.0
logger = logging.getLogger(__name__)

settings_path = os.path.join(os.path.expanduser("~/.openshot_qt"), "openshot.settings")

try:
    if os.path.exists(settings_path):
        with open(settings_path, "r", encoding="utf-8") as fh:
            for item in json.load(fh):
                if item.get("setting") == "ui-scale":
                    scale = float(item.get("value", scale))
                    break
except Exception as exc:
    logger.warning("Failed to read UI scale from %s: %s", settings_path, exc, exc_info=True)
scale = max(0.5, min(3.0, scale))
if scale != 1.0:
    os.environ["QT_SCALE_FACTOR"] = str(scale)

_msix_diagnostic("importing qt_api")
from qt_api import QtCore, QtWidgets
_msix_diagnostic("qt_api import completed")

Qt = QtCore.Qt
QApplication = QtWidgets.QApplication

_msix_diagnostic("importing OpenShot application modules")
try:
    # This must be done before creating QApplication
    QApplication.setAttribute(Qt.AA_ShareOpenGLContexts)
    from OpenGL import GL  # noqa
except (ImportError, AttributeError):
    pass

try:
    # PassThrough lets Qt use the exact QT_SCALE_FACTOR value (e.g. 1.5) without rounding
    # to the nearest integer (e.g. 2.0).
    os.environ['QT_SCALE_FACTOR_ROUNDING_POLICY'] = "PassThrough"

    # Enable High-DPI resolutions
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)
except AttributeError:
    pass  # Quietly fail for older Qt5 versions

try:
    from classes import info
except ImportError:
    import openshot_qt
    sys.path.append(openshot_qt.OPENSHOT_PATH)
    from classes import info

# Global holder for QApplication instance
app = None


def main():
    """"Initialize settings (not implemented) and create main window/application."""

    global app
    _msix_diagnostic("main() entered")

    # Configure argument handling for commandline launches
    parser = argparse.ArgumentParser(description='OpenShot version ' + info.SETUP['version'])
    parser.add_argument(
        '-l', '--lang', action='store',
        help='language code for interface (overrides '
             'preferences and system environment)')
    parser.add_argument(
        '--list-languages', dest='list_languages',
        action='store_true',
        help='List all language codes supported by OpenShot')
    parser.add_argument(
        '--path', dest='py_path', action='append',
        help='Additional locations to search for modules '
             '(PYTHONPATH). Can be used multiple times.')
    parser.add_argument(
        '--test-models', dest='modeltest',
        action='store_true',
        help="Load Qt's QAbstractItemModelTester into data models "
        '(requires Qt 5.11+)')
    parser.add_argument(
        '-d', '--debug', action='store_true',
        help='Enable debugging output')
    parser.add_argument(
        '--debug-file', action='store_true',
        help='Debugging output (logfile only)')
    parser.add_argument(
        '--debug-console', action='store_true',
        help='Debugging output (console only)')
    parser.add_argument('-V', '--version', action='store_true')
    parser.add_argument(
        'remain', nargs=argparse.REMAINDER, help=argparse.SUPPRESS)

    args, extra_args = parser.parse_known_args()

    # Display version and exit (if requested)
    if args.version:
        print(info.SETUP['version'])
        sys.exit()

    # Set up debugging log level to requested streams
    if args.debug or args.debug_file:
        info.LOG_LEVEL_FILE = 'DEBUG'
    if args.debug or args.debug_console:
        info.LOG_LEVEL_CONSOLE = 'DEBUG'

    if args.list_languages:
        from classes.language import get_all_languages
        print("Supported Languages:")
        for code, lang, country in get_all_languages():
            print("  {:>12}  {}".format(code, lang))
        sys.exit()

    if args.py_path:
        for p in args.py_path:
            newpath = os.path.realpath(p)
            try:
                if os.path.exists(newpath):
                    sys.path.insert(0, newpath)
                    print(f"Added {newpath} to PYTHONPATH")
                else:
                    print(f"{newpath} does not exist")
            except TypeError as ex:
                print(f"Bad path {newpath}: {ex}")
                continue

    if args.modeltest:
        info.MODEL_TEST = True
        # Set default logging rules, if the user didn't
        if os.getenv('QT_LOGGING_RULES') is None:
            os.putenv('QT_LOGGING_RULES', 'qt.modeltest.debug=true')
    if args.lang:
        if args.lang in info.SUPPORTED_LANGUAGES:
            info.CMDLINE_LANGUAGE = args.lang
        else:
            print(f"Unsupported language '{args.lang}'! (See --list-languages)")
            sys.exit(-1)

    # Normal startup, print module path and lauch application
    print(f"Loaded modules from: {info.PATH}")

    # Configure packaged CA certificates before optional network integrations start.
    from classes import http_client, sentry
    http_client.configure_ssl_environment()

    # Initialize sentry exception tracing
    sentry.init_tracing()

    # Create any missing paths in the user's settings dir
    info.setup_userdirs()

    # Create Qt application, pass any unprocessed arguments
    _msix_diagnostic("importing classes.app.OpenShotApp")
    from classes.app import OpenShotApp
    _msix_diagnostic("OpenShotApp import completed")

    argv = [sys.argv[0]]
    argv.extend(extra_args)
    argv.extend(args.remain)
    try:
        _msix_diagnostic("constructing OpenShotApp")
        app = OpenShotApp(argv)
        _msix_diagnostic("OpenShotApp construction completed")
    except Exception:
        _msix_diagnostic("OpenShotApp construction raised an exception")
        if _msix_diagnostics:
            traceback.print_exc(file=sys.stderr)
            sys.stderr.flush()
            raise
        app.show_errors()

    # Setup Qt application details
    app.setApplicationName('openshot')
    app.setApplicationVersion(info.VERSION)
    try:
        # Qt 5.7+ only
        app.setDesktopFile("org.openshot.OpenShot")
    except AttributeError:
        pass

    # Launch GUI and start event loop
    _msix_diagnostic("calling app.gui()")
    if app.gui():
        _msix_diagnostic("GUI initialized; entering Qt event loop")
        if hasattr(app, "exec") and callable(app.exec):
            exit_code = app.exec()
        elif hasattr(app, "exec_") and callable(app.exec_):
            exit_code = app.exec_()
        else:
            raise AttributeError("OpenShotApp has no exec_/exec method")
        sys.exit(exit_code)


if __name__ == "__main__":
    main()
