; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#ifndef VERSION
  #define VERSION "0.0.0"
#endif
#ifndef ONLY_64_BIT
  #define ONLY_64_BIT "x64"
#endif
#ifndef PY_EXE_DIR
  #define PY_EXE_DIR "exe.mingw-3.8"
#endif

#define MyAppName "Zenvi"
#define MyAppProjectFileDesc "Zenvi Project File"
#define MyAppPublisher "Zenvi"
#define MyPublisherURL "https://zenvi.org/"
#define MySupportURL "https://zenvi.org/community/"
#define MyAppExeName "zenvi.exe"

#include "isportable.iss"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={code:GetAppId|{{4BB0DCDC-BC24-49EC-8937-72956C33A470}}
AppName={#MyAppName}
AppVersion={#VERSION}
AppVerName={#MyAppName} {#VERSION}
VersionInfoVersion={#VERSION}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyPublisherURL}
AppSupportURL={#MySupportURL}
AppCopyright=(c) 2008-2022 {#MyAppPublisher}
DefaultDirName={code:GetDefaultDirName|Zenvi}
DisableProgramGroupPage=yes
LicenseFile=..\COPYING
OutputBaseFilename=Zenvi
ArchitecturesInstallIn64BitMode={#ONLY_64_BIT}
ArchitecturesAllowed={#ONLY_64_BIT}
ChangesAssociations=not PortableCheck
ChangesEnvironment=not PortableCheck
Compression=lzma
SolidCompression=yes
WizardSmallImageFile=installer-logo.bmp
; NOTE: Keep this path in sync with repo icons.
; The Zenvi repo currently ships `xdg/openshot-qt.ico`.
SetupIconFile=..\xdg\openshot-qt.ico
UsePreviousLanguage=no
Uninstallable=not PortableCheck
UninstallDisplayIcon={app}\{#MyAppExeName}
; CI builds do not have a code-signing tool configured. If SignedUninstaller=yes,
; ISCC will abort and ask for a manual signing step.
; For release signing, re-enable this and configure SignTool in CI.
SignedUninstaller=no
; SignedUninstallerDir=..\build\
PrivilegesRequiredOverridesAllowed=commandline
AllowNoIcons=yes

[Languages]
; CI builds use the default Inno Setup installation which may not include all
; translation `.isl` files. Keep this minimal to ensure deterministic builds.
Name: "english"; MessagesFile: "compiler:Default.isl"

[CustomMessages]
english.FirewallException=Add an exception to the Windows Firewall for optionally sending anonymized usage and error information.

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; Check: not PortableCheck;
Name: "fileassoc"; Description: "{cm:AssocFileExtension,{#MyAppName},.osp}"; GroupDescription: "{cm:AdditionalIcons}"; Check: not PortableCheck;
Name: "firewall"; Description: "{cm:FirewallException}"; GroupDescription: "{cm:AdditionalIcons}"; Check: not PortableCheck;

[InstallDelete]
; Remove previous installed versions of Zenvi
Type: filesandordirs; Name: "{app}\*"
Type: dirifempty; Name: "{app}\*"
Type: files; Name: "{group}\Zenvi"; BeforeInstall: DeleteInvalidFiles; Check: not PortableCheck;

[Registry]
; Associate .zvn files with the installed application. Uninstaller will clean them up, when run.
Root: HKLM; Subkey: "Software\Classes\.zvn"; ValueType: string; ValueName: ""; ValueData: "ZenviProject"; Flags: uninsdeletevalue; Tasks: fileassoc
; .zvn file description, "Zenvi Project File" (ZenviProject, internally)
Root: HKLM; Subkey: "Software\Classes\ZenviProject"; ValueType: string; ValueName: ""; ValueData: "{#MyAppProjectFileDesc}"; Flags: uninsdeletekey; Tasks: fileassoc
; Launcher association for data files of type ZenviProject
Root: HKLM; Subkey: "Software\Classes\ZenviProject\shell\open\command"; ValueType: string;  ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Tasks: fileassoc
; Clean-up old, incorrect AppID Uninstaller (used in 2.6.1-dev builds)
Root: HKLM; Subkey: "Software\Microsoft\Windows\CurrentVersion\Uninstall\4BB0DCDC-BC24-49EC-8937-72956C33A470_is1"; ValueName: ""; Flags: deletekey;

[Files]
; Add all frozen files from cx_Freeze build
Source: "..\build\{#PY_EXE_DIR}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Check: not WizardNoIcons;
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; Check: not WizardNoIcons;

[Run]
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=""{#MyAppName}"" program=""{app}\{#MyAppExeName}"" dir=in action=allow enable=yes"; Flags: runhidden; Tasks: firewall;
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#MyAppName}"""; Flags: runhidden; Tasks: firewall;

[Code]
procedure DeleteInvalidFiles();
begin
  if (FileExists (ExpandConstant('{sys}\zlib1.dll'))) then
  begin
    RenameFile(ExpandConstant('{sys}\zlib1.dll'), ExpandConstant('{sys}\zlib1.DELETE'));
  end;
  if (FileExists (ExpandConstant('{win}\system32\zlib1.dll'))) then
  begin
    RenameFile(ExpandConstant('{win}\system32\zlib1.dll'), ExpandConstant('{win}\system32\zlib1.DELETE'));
  end;
  if (FileExists (ExpandConstant('{syswow64}\zlib1.dll'))) then
  begin
    RenameFile(ExpandConstant('{syswow64}\zlib1.dll'), ExpandConstant('{syswow64}\zlib1.DELETE'));
  end;
end;
